let bookTitle :string = "TypeScript Basics";
const libraryName: string = "My library";
let numberOfBooks : number = 18;
let isLibraryOpen:boolean = true;

let titulo:string = "1984"
let autor:string = "George Orwell";
let genero:string= "Ficción, Ciencia Ficción";
let idioma: string="Inglés";
let precio: number = 25000;
let formato: string = "Tapa dura";
let isbn: string = "978-0451524935";
let descripcion: string = "Novela distópica que describe una sociedad totalitaria en la que el gobierno controla todos los aspectos de la vida de los ciudadanos.";
let estado: string = "Nuevo";
let ubicacion:  string =  "Biblioteca central";
let fecha_publicacion:Date = new Date(1949, 6, 8);
let editorial: string ="Secker and Warburg";
let paginas:number = 328;
let dimensiones: string = "13.5 x 21.5 x 3.5 cm"
let peso: string = "450 gramos"
let disponible:boolean =  true;
